spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?characterEncoding=utf8&useSSL=false&&useunicode=true&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: mapper/AopMapper.xml
  type-aliases-package: com/example/aopdemo/entities
